### ISSUE TITLE
Issues locating counter.json

### ISSUE THREAD

**Issue by Vulpicula** [Vabolos/DeathCounter-mcplugin#1]
Heya!

I've just installed this little plugin, and while it works fine, it appears to have issues saving.

My environment is Ubuntu Server 22, which is running a Pterodactyl instance that hosts a Purpur server for Minecraft 1.20.4. (Quite a mouthful!) The error in question is as follows:

> [23:54:53 ERROR]: [DeathCount] Error saving death counts to file
java.io.FileNotFoundException: plugins/DeathCount/..\counter.json (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method) ~[?:?]
        at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
        at java.io.FileWriter.<init>(FileWriter.java:96) ~[?:?]
        at deathcount.deathcount.DeathCount.saveDeathCounts(DeathCount.java:108) ~[DeathCount.jar:?]
        at deathcount.deathcount.DeathCount.onPlayerQuit(DeathCount.java:104) ~[DeathCount.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2149]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:614) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:598) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2164) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2144) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2131) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:846) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1771) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
        
The fix seems to literally be adding the "DeathCounter" folder in /plugins/, as it doesn't appear to want to create it automatically. I am unsure as to why.

**Comment by konstkarapan** [comment]
> Heya!
> 
> I've just installed this little plugin, and while it works fine, it appears to have issues saving.
> 
> My environment is Ubuntu Server 22, which is running a Pterodactyl instance that hosts a Purpur server for Minecraft 1.20.4. (Quite a mouthful!) The error in question is as follows:
> 
> > [23:54:53 ERROR]: [DeathCount] Error saving death counts to file
> java.io.FileNotFoundException: plugins/DeathCount/..\counter.json (No such file or directory)
>         at java.io.FileOutputStream.open0(Native Method) ~[?:?]
>         at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
>         at java.io.FileWriter.<init>(FileWriter.java:96) ~[?:?]
>         at deathcount.deathcount.DeathCount.saveDeathCounts(DeathCount.java:108) ~[DeathCount.jar:?]
>         at deathcount.deathcount.DeathCount.onPlayerQuit(DeathCount.java:104) ~[DeathCount.jar:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2149]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
>         at net.minecraft.server.players.PlayerList.remove(PlayerList.java:614) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at net.minecraft.server.players.PlayerList.remove(PlayerList.java:598) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2164) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2144) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2131) ~[?:?]
>         at net.minecraft.network.Connection.handleDisconnection(Connection.java:846) ~[?:?]
>         at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
>         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1771) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2149]
>         at java.lang.Thread.run(Thread.java:840) ~[?:?]
>         
> The fix seems to literally be adding the "DeathCounter" folder in /plugins/, as it doesn't appear to want to create it automatically. I am unsure as to why.
> 

Small correction. The folder has to be named "DeathCount" and not "DeathCounter"
